# Generated by Django 4.1.5 on 2023-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0002_boroughs_remove_userinhaler_inhaler_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='home_postcode',
            field=models.CharField(default=234, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='other_postcode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='work_postcode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
