# Generated by Django 3.2.9 on 2022-12-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='Clear.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_users', to='Clear.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_users', to='Clear.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_users', to='Clear.location'),
        ),
    ]
