# Generated by Django 3.2.9 on 2022-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0003_auto_20221229_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('low_dose', models.IntegerField()),
                ('low_puffs', models.IntegerField()),
                ('low_frequency', models.IntegerField()),
                ('med_dose', models.IntegerField()),
                ('med_puffs', models.IntegerField()),
                ('med_frequency', models.IntegerField()),
                ('hi_dose', models.IntegerField()),
                ('hi_puffs', models.IntegerField()),
                ('hi_frequency', models.IntegerField()),
            ],
        ),
    ]
