# Generated by Django 3.2.9 on 2022-12-29 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0004_inhaler'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionLevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=128)),
                ('lower_bound', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('general_description', models.CharField(max_length=512)),
                ('risk_description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='UserInhaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puffs_today', models.IntegerField(default=0)),
                ('puffs_remaining', models.IntegerField()),
                ('dose', models.IntegerField()),
                ('puffs', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('inhaler_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhaler_users', to='Clear.inhaler')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inhalers', to='Clear.userprofile')),
            ],
        ),
    ]
