# Generated by Django 3.2.9 on 2022-12-29 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0005_auto_20221229_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollution_level', models.IntegerField()),
                ('pollution_date', models.DateField(default=datetime.date.today)),
                ('current_flag', models.BooleanField(default=True)),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pollution', to='Clear.location')),
            ],
        ),
    ]
