# Generated by Django 3.2.9 on 2022-12-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0006_pollutionlevels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollutionlevels',
            old_name='loc_id',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_loc',
            new_name='current_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='home_loc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='other_loc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work_loc',
        ),
        migrations.AlterField(
            model_name='pollutionlevelinfo',
            name='band',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userinhaler',
            name='dose',
            field=models.IntegerField(help_text='Dose in micrograms'),
        ),
        migrations.AlterField(
            model_name='userinhaler',
            name='frequency',
            field=models.IntegerField(help_text='Number of uses per day'),
        ),
        migrations.AlterField(
            model_name='userinhaler',
            name='inhaler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_inhaler', to='Clear.inhaler'),
        ),
        migrations.AlterField(
            model_name='userinhaler',
            name='puffs',
            field=models.IntegerField(help_text='Number of puffs per usage'),
        ),
        migrations.AlterField(
            model_name='userinhaler',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhalers_user', to='Clear.userprofile'),
        ),
        migrations.CreateModel(
            name='UserLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=5)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_location', to='Clear.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_user', to='Clear.userprofile')),
            ],
        ),
    ]
